name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup SSH ğŸ”
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 ğŸš€
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            sudo yum update -y
            sudo yum install -y git python3
            cd /home/ec2-user/

            # Kalau folder sudah ada, masuk dan git pull
            if [ -d "UTS-ecommerce-aws" ]; then
              cd UTS-ecommerce-aws
              git pull origin main
            else
              git clone https://github.com/bayuramdhan50/UTS-ecommerce-aws.git
              cd UTS-ecommerce-aws
            fi

            # Kill app.py jika masih jalan
            sudo pkill -f app.py || true

            # Start ulang
            nohup python3 app.py > output.log 2>&1 &
          EOF
